name: ci
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build-and-test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go: ['1.14.x']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout gobuild
        uses: actions/checkout@v2
        with:
          repository: ctrl-cmd/gobuild
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./build/gobuild

      - name: Replace gobuild
        working-directory: ./build
        run: go mod edit -replace=github.com/ctrl-cmd/gobuild=./gobuild

      - name: Install golangci-lint
        run: |
          wget -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
          sh install.sh
      
      - name: Run linter
        run: ./bin/golangci-lint run ./...

      - name: Build
        working-directory: ./build
        run: go run ./mage.go build

      - name: Tests
        working-directory: ./build
        run: go run ./mage.go test:integration

  build-docker-release-images:
    needs: build-and-test
    # build docker images for tag push only
    strategy:
      matrix:
        platform: [ubuntu-latest]
        cfg:
          - { arch: amd64,   goarch: amd64 }
          - { arch: i386,    goarch: 386 }
          - { arch: ppc64le, goarch: ppc64le }
          - { arch: arm64v8, goarch: arm64 }
          - { arch: arm32v7, goarch: arm }
          - { arch: s390x,   goarch: s390x }
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout gobuild
        uses: actions/checkout@v2
        with:
          repository: ctrl-cmd/gobuild
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./build/gobuild

      - name: Build Docker image [${{ matrix.cfg.arch }}]
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./build/docker/Dockerfile
          registry: docker.pkg.github.com
          repository: ctrl-cmd/spks/spks
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          build_args: ALPINE_ARCH=${{ matrix.cfg.arch }},BUILD_GOARCH=${{ matrix.cfg.goarch }}
          tag_with_ref: ${{ startsWith(github.ref, 'refs/tags/') }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
